const detaineeData = {
  "meta": {
    "source": "وزارة الداخلية السورية",
    "sourceHandle": "syrianmoi",
    "sourceUrl": "https://x.com/syrianmoi",
    "asOf": "2025-06-15",
    "totalDetainees": 5989,
    "rankedTotal": 3696,
    "_note": "الأسماء والتهم منقولة بصريا من منشورات وزارة الداخلية. يرجى التدقيق قبل النشر. _note يُحذف من الواجهة."
  },
  "ranks": [
    { "ar": "عماد", "count": 1 },
    { "ar": "لواء", "count": 42 },
    { "ar": "عميد", "count": 172 },
    { "ar": "عقيد", "count": 218 },
    { "ar": "مقدم", "count": 112 },
    { "ar": "رائد", "count": 73 },
    { "ar": "نقيب", "count": 160 },
    { "ar": "ملازم أول", "count": 126 },
    { "ar": "ملازم", "count": 32 },
    { "ar": "مساعد أول", "count": 435 },
    { "ar": "مساعد", "count": 268 },
    { "ar": "رقيب أول", "count": 174 },
    { "ar": "رقيب", "count": 285 },
    { "ar": "عريف", "count": 160 },
    { "ar": "عنصر", "count": 1438 }
  ],
  "individuals": [
    { "name": "عاطف نجيب", "role": "رئيس فرع الأمن السياسي في درعا", "photo": "/assets/justice/26.jpg" },
    { "name": "أمجد يوسف", "role": "المتهم الأول بارتكاب مجزرة التضامن", "photo": "/assets/justice/23.jpg" },
    { "name": "محمد الشعار", "role": "شغل منصب وزير الداخلية في عهد النظام السابق", "photo": "/assets/justice/22.jpg" },
    { "name": "وسيم الأسد", "role": "ارتبط اسمه باتهامات بالفساد وتجارة المخدرات", "photo": "/assets/justice/24.jpg" },
    { "name": "موفق نظير حيدر", "role": "لواء سابق وقائد الفرقة الثالثة دبابات، ارتبط اسمه بحجز الغوطة وعمليات الاقتحام", "photo": "/assets/justice/1.jpg" },
    { "name": "عامر إبراهيم العشي", "role": "لواء، شغل منصب مسؤول فرع المعلومات في المخابرات خلال عهد النظام السابق", "photo": "/assets/justice/2.jpg" },
    { "name": "راتب علي غانم", "role": "عميد سابق ومعاون رئيس فرع سعسع", "photo": "/assets/justice/3.jpg" },
    { "name": "غيث سليمان شاهين", "role": "عميد ركن، ارتبط اسمه بأحداث القصف على مدينة القصير", "photo": "/assets/justice/4.jpg" },
    { "name": "طلال محسن علي", "role": "عميد ركن، شغل منصب رئيس فرع سعسع", "photo": "/assets/justice/5.jpg" },
    { "name": "محمد محسن نيوف", "role": "رئيس أركان الفرقة 11 عام 2020 وقائد الفرقة 18 دبابات", "photo": "/assets/justice/6.jpg" },
    { "name": "عبد الوهاب عثمان", "role": "القوى الجوية، قائد المقر الموحد الشمالي", "photo": "/assets/justice/7.jpg" },
    { "name": "نائف صالح درغام", "role": "لواء، شغل منصب النائب العام العسكري خلال عهد النظام السابق", "photo": "/assets/justice/8.jpg" },
    { "name": "جايز حمود الموسى", "role": "تولى قيادة أركان القوات الجوية", "photo": "/assets/justice/9.jpg" },
    { "name": "أكرم سلوم العبد الله", "role": "شغل منصب قائد الشرطة العسكرية", "photo": "/assets/justice/10.jpg" },
    { "name": "آصف رفعت سالم", "role": "متورط في جرائم حرب ارتكبت في الزبداني ومضايا", "photo": "/assets/justice/11.jpg" },
    { "name": "سهيل فجر حسن", "role": "قيادة كتيبة في الحرس الجمهوري", "photo": "/assets/justice/12.jpg" },
    { "name": "واصل العويد", "role": "عمل نائبا لرئيس الأركان", "photo": "/assets/justice/13.jpg" },
    { "name": "إبراهيم محلا", "role": "رئيس أركان الفرقة 22", "photo": "/assets/justice/14.jpg" },
    { "name": "خردل أحمد ديوب", "role": "متورط في الهجوم الكيميائي على الغوطة الشرقية", "photo": "/assets/justice/15.jpg" },
    { "name": "ميزر صوان", "role": "لواء طيار سابق متورط في إصدار أوامر بقصف مناطق الغوطتين", "photo": "/assets/justice/16.jpg" },
    { "name": "حمزة محمد الياسين", "role": "عميد طيار سابق وارتبط اسمه بمجازر بحق السوريين", "photo": "/assets/justice/17.jpg" },
    { "name": "راتب فهد الحسين", "role": "شغل منصب رئيس مفرزة الأمن العسكري في محردة", "photo": "/assets/justice/18.jpg" },
    { "name": "بشار ميهوب", "role": "متورط في تنفيذ عمليات اغتيال استهدفت عناصر من قوى الأمن الداخلي", "photo": "/assets/justice/19.jpg" },
    { "name": "عماد نفوري", "role": "قائد اللواء الجوي 17 ومدير إدارة العمليات الجوية", "photo": "/assets/justice/20.jpg" },
    { "name": "تيسير عبد الحميد", "role": "عميد سابق في المخابرات الجوية", "photo": "/assets/justice/21.jpg" },
    { "name": "عدنان عبود حلوة", "role": "أبرز المسؤولين عن الهجوم الكيميائي على الغوطة الشرقية", "photo": "/assets/justice/25.jpg" },
    { "name": "وجيه علي العبد الله", "role": "لواء سابق ومدير مكتب الشؤون العسكرية لدى بشار الأسد", "photo": "/assets/justice/27.jpg" },
    { "name": "تركي مخلف العمر", "role": "قوات مقاتلي العشائر التابعة للأمن العسكري", "photo": "/assets/justice/28.jpg" },
    { "name": "رياض عبد الله يوسف", "role": "لواء طيار سابق وقائد مطار الضمير العسكري", "photo": "/assets/justice/29.jpg" },
    { "name": "سامي أوبري", "role": "أحد قادة ميليشيا الدفاع الوطني في حلب", "photo": "/assets/justice/30.jpg" },
    { "name": "شجاع إبراهيم", "role": "ارتبط اسمه بجرائم قتل واعتقال تعسفي", "photo": "/assets/justice/31.jpg" },
    { "name": "الوضاح سميل إسماعيل", "role": "أحد قادة المجموعات الخارجة عن القانون", "photo": "/assets/justice/32.jpg" },
    { "name": "رامي منير إسماعيل", "role": "عميد سابق ورئيس فرع المخابرات الجوية", "photo": "/assets/justice/33.jpg" },
    { "name": "رياض حمدو الشحادة", "role": "عميد سابق في جهاز الأمن السياسي", "photo": "/assets/justice/34.jpg" },
    { "name": "منذر الجزائري", "role": "تثبت تورطه في مجزرة التضامن التي وقعت خلال عهد النظام السابق", "photo": "/assets/justice/35.jpg" },
    { "name": "أسعد شريف عباس", "role": "ارتبط اسمه بمجزرة التضامن خلال عهد النظام السابق", "photo": "/assets/justice/36.jpg" },
    { "name": "نمير بديع الأسد", "role": "متورط في جرائم قتل وخطف وابتزاز وسلب مسلح", "photo": "/assets/justice/37.jpg" },
    { "name": "فياض الغانم", "role": "قائد ميليشيا صقور الرقة خلال عهد النظام السابق", "photo": "/assets/justice/38.jpg" },
    { "name": "خالد عثمان", "role": "مجرم حرب وعضو في خلية للخطف والسلب نشطت بعد سقوط البلاد", "photo": "/assets/justice/39.jpg" },
    { "name": "قصي وجيه إبراهيم", "role": "عقيد سابق وقائد كتيبة الجبل", "photo": "/assets/justice/40.jpg" },
    { "name": "بشار محفوض", "role": "متورط في جرائم حرب وتشكيل عصابة للخطف والسلب عقب سقوط النظام", "photo": "/assets/justice/41.jpg" },
    { "name": "سالم اسكندر", "role": "شغل منصب مسؤول فرع أمن الدولة في مدينة الصنمين خلال عهد النظام السابق", "photo": "/assets/justice/42.jpg" },
    { "name": "تيسير عثمان محفوظ", "role": "عميد، رئيس مفرزة في الفرع 215 التابع للاستخبارات العسكرية", "photo": "/assets/justice/43.jpg" },
    { "name": "أمر يوسف الحسن", "role": "عميد سابق في فرع أمن الدولة باللاذقية", "photo": "/assets/justice/44.jpg" },
    { "name": "نزار شاهين شاهين", "role": "عميد ركن، ارتبط اسمه بأحداث وانتهاكات وقعت في القصير", "photo": "/assets/justice/45.jpg" },
    { "name": "سالم نورس داغستاني", "role": "عميد ركن، رئيس فرع التحقيق في المخابرات الجوية خلال عهد النظام السابق", "photo": "/assets/justice/46.jpg" },
    { "name": "دعاس حسين علي", "role": "عميد سابق، شغل منصب رئيس فرع أمن الدولة في دير الزور", "photo": "/assets/justice/47.jpg" },
    { "name": "محمد عماد محرز", "role": "عمل سجانا في سجن صيدنايا العسكري", "photo": "/assets/justice/48.jpg" },
    { "name": "رفيق أحمد كلثوم", "role": "لواء سابق في قوات النظام السابق", "photo": "/assets/justice/49.jpg" },
    { "name": "عيسى غنام", "role": "متورط في تسريب إحداثيات معسكر للثوار في كفرتخاريم عام 2020", "photo": "/assets/justice/50.jpg" },
    { "name": "فادي معروف", "role": "متورط في تسريب إحداثيات معسكر للثوار في كفرتخاريم عام 2020", "photo": "/assets/justice/51.jpg" },
    { "name": "عبد الإله إسماعيل الحمد", "role": "قائد تشكيل في ميليشيا لواء القدس، متورط بجرائم حرب وخطف وتعذيب", "photo": "/assets/justice/52.jpg" },
    { "name": "رأفت أنور العامودي", "role": "من أبرز المطلوبين، عمل لصالح ميليشيا اللجان الشعبية في درعا", "photo": "/assets/justice/53.jpg" },
    { "name": "قيس حسان العبد الرجب", "role": "لواء، معاون مدير إدارة المخابرات العامة (أمن الدولة)", "photo": "/assets/justice/54.jpg" },
    { "name": "ساري مؤيد مخلوف", "role": "متورط في مجزرة البيضا في بانياس وجرائم سلب وخطف", "photo": "/assets/justice/55.jpg" }
  ],
  "hierarchy": {
    "source": "القائمة السوداء - منظمة مع العدالة (Pro-Justice)",
    "sourceUrl": "https://blacklist.pro-justice.org/ar/",
    "root": { "name": "بشار الأسد", "role": "رئيس النظام ولاجئ في موسكو", "photo": "/assets/justice/tree/bashar.jpg" },
    "groups": [
      {
        "title": "المخابرات والأمن",
        "members": [
          { "name": "علي مملوك", "role": "مدير مكتب الأمن الوطني", "photo": "/assets/justice/tree/p1.jpg" },
          { "name": "جميل حسن", "role": "مدير إدارة المخابرات الجوية", "photo": "/assets/justice/tree/p2.jpg" },
          { "name": "محمد ديب زيتون", "role": "مدير إدارة أمن الدولة" },
          { "name": "عبدالفتاح سليمان قدسية", "role": "نائب مدير مكتب الأمن الوطني" },
          { "name": "غسان جودت اسماعيل", "role": "نائب مدير إدارة المخابرات الجوية", "photo": "/assets/justice/tree/p5.jpg" },
          { "name": "أديب نمر سلامة", "role": "معاون مدير إدارة المخابرات الجوية", "photo": "/assets/justice/tree/p6.jpg" },
          { "name": "نزيه حسون", "role": "تم تسريحه من رئاسة شعبة الأمن السياسي" },
          { "name": "توفيق يونس", "role": "متقاعد" },
          { "name": "محمد محمود محلا", "role": "رئيس شعبة المخابرات العسكرية", "photo": "/assets/justice/tree/p9.jpg" },
          { "name": "علي ونوس", "role": "قائد الوحدة 450" },
          { "name": "رياض حبيب عباس", "role": "قائد الشرطة العسكرية", "photo": "/assets/justice/tree/p11.jpg" },
          { "name": "غسان خليل", "role": "معاون مدير إدارة أمن الدولة" },
          { "name": "كفاح ملحم", "role": "معاون رئيس شعبة المخابرات العسكرية" },
          { "name": "جودت إبراهيم الصافي", "role": "رئيس فرع الأمن السياسي - ريف دمشق" },
          { "name": "جودت الأحمد", "role": "إدارة المخابرات الجوية" },
          { "name": "حافظ محمد مخلوف", "role": "ضابط في إدارة المخابرات العامة", "photo": "/assets/justice/tree/p16.jpg" },
          { "name": "قصي إبراهيم ميهوب", "role": "ضابط في إدارة المخابرات الجوية", "photo": "/assets/justice/tree/p17.jpg" },
          { "name": "لؤي العلي", "role": "رئيس فرع الأمن العسكري في السويداء", "photo": "/assets/justice/tree/p18.jpg" },
          { "name": "مازن هواش الكنج", "role": "رئيس فرع الأمن العسكري في حلب", "photo": "/assets/justice/tree/p19.jpg" },
          { "name": "محمد زمريني", "role": "رئيس فرع الدوريات - شعبة المخابرات العسكرية" },
          { "name": "وفيق ناصر", "role": "رئيس الفرع 219 - فرع المخابرات العسكرية في حماه", "photo": "/assets/justice/tree/p21.jpg" },
          { "name": "مفيد وردة", "role": "نائب رئيس فرع الأمن العسكري في حمص", "photo": "/assets/justice/tree/p22.jpg" },
          { "name": "سهيل الحسن", "role": "رئيس فرع المخابرات الجوية في المنطقة الشمالية", "photo": "/assets/justice/tree/p23.jpg" },
          { "name": "ياسين أحمد ضاحي", "role": "رئيس فرع المخابرات العسكرية في دير الزور", "photo": "/assets/justice/tree/p24.jpg" },
          { "name": "عبد السلام فجر محمود", "role": "رئيس فرع" },
          { "name": "محمد خلوف", "role": "شعبة المخابرات العسكرية", "photo": "/assets/justice/tree/p26.jpg" },
          { "name": "شفيق مصة", "role": "رئيس فرع المداهمة والاقتحام، الفرع 215 - شعبة المخابرات العسكرية", "photo": "/assets/justice/tree/p27.jpg" },
          { "name": "نوفل الحسين", "role": "متقاعد عن الخدمة" },
          { "name": "فراس غسان جزعة", "role": "قائد قوات درع القلمون", "photo": "/assets/justice/tree/p29.jpg" },
          { "name": "محمد ابراهيم الشعار", "role": "وزير الداخلية السابق في حكومة النظام", "photo": "/assets/justice/tree/p30.jpg" },
          { "name": "ناصر ديب", "role": "رئيس شعبة الأمن السياسي", "photo": "/assets/justice/tree/p31.jpg" },
          { "name": "اللواء أكرم محمد", "role": "رئيس فرع أمن الدولة في طرطوس إدارة المخابرات العامة", "photo": "/assets/justice/tree/p32.jpg" },
          { "name": "العميد ابراهيم الوعري", "role": "رئيس فرع الأمن العسكري في حمص" },
          { "name": "العميد إياد اسكندر مندو", "role": "الجيش والقوات والمسلحة-إدارة المخابرات الجوية" },
          { "name": "العميد المهندس سليمان التيناوي", "role": "رئيس فرع المعلومات إدارة المخابرات الجوية", "photo": "/assets/justice/tree/p35.jpg" },
          { "name": "العميد عدنان الأحمد", "role": "رئيس فرع الدوريات الفرع 216 شعبة المخابرات العسكرية" },
          { "name": "حسام لوقا", "role": "مديـر إدارة المخابرات العامة", "photo": "/assets/justice/tree/p37.jpg" }
        ]
      },
      {
        "title": "الجيش والقوات المسلحة",
        "members": [
          { "name": "ماهر الأسد", "role": "قائد الفرقة الرابعة المدرعة", "photo": "/assets/justice/tree/maher.jpg" },
          { "name": "فهد جاسم الفريج", "role": "متقاعد", "photo": "/assets/justice/tree/fahd.jpg" },
          { "name": "علي عبد الله أيوب", "role": "نائب القائد العام - وزير الدفاع", "photo": "/assets/justice/tree/ayyoub.jpg" },
          { "name": "طلال شفيق مخلوف", "role": "قائد الحرس الجمهوري", "photo": "/assets/justice/tree/p38.jpg" },
          { "name": "جمال محمود يونس", "role": "رئيس اللجنة الأمنية والعسكرية في المنطقة الشرقية", "photo": "/assets/justice/tree/p39.jpg" },
          { "name": "رفيق محمود شحادة", "role": "تحت تصرف القائد العام للجيش والقوات المسلحة", "photo": "/assets/justice/tree/p40.jpg" },
          { "name": "وجيه يحيى محمود", "role": "تم تسريحه مؤخراً", "photo": "/assets/justice/tree/p41.jpg" },
          { "name": "زيد صالح", "role": "نائب قائد الحرس الجمهوري - قائد الفيلق الخامس", "photo": "/assets/justice/tree/p42.jpg" },
          { "name": "رمضان الرمضان", "role": "قائد الفرقة التاسعة دبابات", "photo": "/assets/justice/tree/p43.jpg" },
          { "name": "موفق محمد أسعد", "role": "مستشار في وزارة الدفاع", "photo": "/assets/justice/tree/p44.jpg" },
          { "name": "أوس علي أصلان", "role": "قائد الفيلق الثاني في الجيش العربي السوري", "photo": "/assets/justice/tree/p45.jpg" },
          { "name": "جودت صليبي مواس", "role": "ضابط في إدارة المدفعية والصواريخ" },
          { "name": "محمد ابراهيم خضور", "role": "قائد الفيلق الثالث - رئيس الجنة الأمنية في حمص وريفها", "photo": "/assets/justice/tree/p47.jpg" },
          { "name": "محمد خالد رحمون", "role": "وزير الداخلية السورية", "photo": "/assets/justice/tree/p48.jpg" },
          { "name": "بسام حيدر", "role": "قائد الفرقة 20 قوى جوية", "photo": "/assets/justice/tree/p49.jpg" },
          { "name": "أحمد محمد بللول", "role": "قائد القوى الجوية والدفاع الجوي", "photo": "/assets/justice/tree/p50.jpg" },
          { "name": "بسام مرهج الحسن", "role": "مدير المكتب الأمني والعسكري في القصر الجمهوري", "photo": "/assets/justice/tree/p51.jpg" },
          { "name": "جمعة محمد الجاسم", "role": "تمت إقالته بنهاية شهر آب من عام 2018 بعد تمديد", "photo": "/assets/justice/tree/p52.jpg" },
          { "name": "حسن مرهج مرهج", "role": "قائد الفيلق الرابع - اقتحام", "photo": "/assets/justice/tree/p53.jpg" },
          { "name": "علي أحمد أسعد", "role": "قائد الفرقة 15 قوات خاصة", "photo": "/assets/justice/tree/p54.jpg" },
          { "name": "محمد كنجو حسن", "role": "مدير إدارة القضاء العسكري" },
          { "name": "مالك عليا", "role": "رئيس اللجنة الأمنية والعسكرية في حلب قائد الفرقة 30 حرس جمهوري", "photo": "/assets/justice/tree/p56.jpg" },
          { "name": "غسان علي بلال", "role": "مدير مكتب الأمن في الفرقة الرابعة قائد الفوج 555 مظلي" },
          { "name": "الدكتور غسان حداد", "role": "مدير مشفى الشهيد يوسف العظمة (المشفى 601 العسكري) ويعرف أيضاً باسم مشفى المزة العسكري", "photo": "/assets/justice/tree/p58.jpg" },
          { "name": "فايز بدور", "role": "ضابط في الوحدات الخاصة" },
          { "name": "أكثم محمود", "role": "رئيس أركان فوج المهام الخاصة في الفيلق الخامس", "photo": "/assets/justice/tree/p60.jpg" },
          { "name": "نزار علي فندي", "role": "قائد الكتيبة 103 - الفرقة التاسعة", "photo": "/assets/justice/tree/p61.jpg" },
          { "name": "غياث سليمان دلّا", "role": "قائد قوات الغيث في الفرقة الرابعة", "photo": "/assets/justice/tree/p62.jpg" },
          { "name": "دريد إسماعيل عوض", "role": "قائد قوات المدفعية في قوات", "photo": "/assets/justice/tree/p63.jpg" },
          { "name": "واصل خالد السمير العويد", "role": "نائب رئيس هيئة الأركان العامة مكلف بتسيير أمور هيئة الأركان العامة", "photo": "/assets/justice/tree/p64.jpg" },
          { "name": "سليم حربا", "role": "نائب رئيس هيئة الأركان العامة رئيس اللجنة الأمنية والعسكرية في حلب", "photo": "/assets/justice/tree/p65.jpg" },
          { "name": "شوقي أحمد يوسف", "role": "نائب رئيس هيئة العمليات قائد المنطقة الشرقية", "photo": "/assets/justice/tree/p66.jpg" },
          { "name": "مالك حسن", "role": "ضابط في قيادة القوى الجوية" },
          { "name": "اللواء المظلي فؤاد أحمد حمودة", "role": "ضابط في الجيش السوري-القوات الخاصة" },
          { "name": "اللواء عدنان جميل اسماعيل", "role": "قائد الفرقة الثالثة", "photo": "/assets/justice/tree/p69.jpg" },
          { "name": "اللواء حكمت موسى سلمان", "role": "قائد الفرقة السابعة ميكا", "photo": "/assets/justice/tree/p70.jpg" },
          { "name": "اللواء حسن محمد محمد", "role": "قائد الفيلق الثالث رئيس اللجنة الأمنية والعسكرية في حمص", "photo": "/assets/justice/tree/p71.jpg" },
          { "name": "العميد محمد يوسف الحاصوري", "role": "نائب قائد اللواء 50 - الفرقة 22", "photo": "/assets/justice/tree/p72.jpg" },
          { "name": "اللواء حسان بديع علي", "role": "قائد القوى الجوية والدفاع الجوي", "photo": "/assets/justice/tree/p73.jpg" }
        ]
      },
      {
        "title": "الميليشيات والشبيحة",
        "members": [
          { "name": "زهير الأسد", "role": "لواء، خدم في سرايا الدفاع سابقاً", "photo": "/assets/justice/tree/p74.jpg" },
          { "name": "صايل أسعد داوود", "role": "مشرف على الدفاع الوطني في حمص" },
          { "name": "صالح العبدالله", "role": "ضابط العمليات في قوات النمر", "photo": "/assets/justice/tree/p76.jpg" },
          { "name": "صالح صقر", "role": "مشرف على الدفاع وطني في حماه وحمص" },
          { "name": "صقر رستم", "role": "أمين عام الدفاع الوطني", "photo": "/assets/justice/tree/p78.jpg" },
          { "name": "المهندس محمد أحمد السعيد", "role": "قائد لواء القدس الفلسطيني ميليشيات", "photo": "/assets/justice/tree/p79.jpg" },
          { "name": "فادي الملاح", "role": "قائد قوات الجليل (ميليشيا فلسطينية تقاتل إلى جانب قوات النظام السوري)", "photo": "/assets/justice/tree/p80.jpg" },
          { "name": "الشبيح علي الشلي", "role": "قائد مجموعة الصقر في قوات النمر متعاقد مع المخابرات الجوية", "photo": "/assets/justice/tree/p81.jpg" },
          { "name": "مصيب نمر سلامة", "role": "قائد مجموعة شبيحة في السلمية", "photo": "/assets/justice/tree/p82.jpg" }
        ]
      },
      {
        "title": "رجال الأعمال وتمويل النظام",
        "members": [
          { "name": "رامي محمد مخلوف", "role": "رجل أعمال", "photo": "/assets/justice/tree/p83.jpg" },
          { "name": "حسام أحمد قاطرجي", "role": "رجل أعمال", "photo": "/assets/justice/tree/p84.jpg" },
          { "name": "فادي صقر", "role": "رجل أعمال", "photo": "/assets/justice/tree/fadi_saqr.jpg" },
          { "name": "محمد حمشو", "role": "رجل أعمال وحرامي حديد", "photo": "/assets/justice/tree/hamsho.jpg" }
        ]
      }
    ]
  }
} as const;

export default detaineeData;

/*
PORT STATUS
  source:     resources/js/Pages/Justice/_data/detainees.json (201 lines)
  confidence: high
  todos:      0
  notes:      JSON is bundled as a typed native data module without changing records.
*/
