brotli on;
brotli_static on;
brotli_comp_level 4;
brotli_types text/plain text/css text/javascript application/javascript application/x-javascript text/xml application/xml application/xml+rss application/json image/svg+xml;
