server {
    listen 8080 default_server;
    listen [::]:8080 default_server;
    server_name _;
    root /var/www/html/public;

    index index.php index.html;

    charset utf-8;

    # Dynamic static file caching
    location /build/ {
        expires max;
        access_log off;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    # Pass all standard traffic to index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Health check endpoint for container platform
    location = /healthcheck {
        access_log off;
        add_header Content-Type text/plain;
        return 200 'OK';
    }

    # Pass PHP scripts to PHP-FPM using the base image's predefined upstream
    location ~ \.php$ {
        fastcgi_pass php-fpm;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
