export const PROVINCE_TO_PCODE: { [key: string]: string } = {
    // English Normalizations
    'damascus': 'SY01',
    'aleppo': 'SY02',
    'rural damascus': 'SY03',
    'rif dimashq': 'SY03',
    'homs': 'SY04',
    'hama': 'SY05',
    'lattakia': 'SY06',
    'latakia': 'SY06',
    'idlib': 'SY07',
    'idleb': 'SY07',
    'al hasakah': 'SY08',
    'hasakah': 'SY08',
    'deir ez-zor': 'SY09',
    'deir ezzor': 'SY09',
    'tartous': 'SY10',
    'tartus': 'SY10',
    'ar raqqah': 'SY11',
    'raqqa': 'SY11',
    'daraa': 'SY12',
    'dar\'a': 'SY12',
    'as suwayda': 'SY13',
    'as suwayda\'': 'SY13',
    'sweida': 'SY13',
    'quneitra': 'SY14',
    'al qunaytirah': 'SY14',
    
    // Arabic Normalizations
    'دمشق': 'SY01',
    'حلب': 'SY02',
    'ريف دمشق': 'SY03',
    'حمص': 'SY04',
    'حماة': 'SY05',
    'اللاذقية': 'SY06',
    'إدلب': 'SY07',
    'الحسكة': 'SY08',
    'دير الزور': 'SY09',
    'طرطوس': 'SY10',
    'الرقة': 'SY11',
    'درعا': 'SY12',
    'السويداء': 'SY13',
    'القنيطرة': 'SY14'
};