// AUTO-GENERATED by scripts/export-compass-data.mjs — do not edit by hand.
import type { AlignQuestion } from './types';

export const ALIGN_QUESTIONS: AlignQuestion[] = [
  { text: "التحالف مع أمريكا وأوروبا يخدم إعمار سوريا.", target: "west", tier: 3, weight: 1 },
  { text: "يجب التقارب مع السعودية والخليج لجلب الاستثمار.", target: "gulf", tier: 3, weight: 1 },
  { text: "التحالف مع تركيا وقطر يفيد سوريا أكثر من أي طرف.", target: "turkish", tier: 3, weight: 1 },
  { text: "يجب مواصلة التقارب مع روسيا للحفاظ على القواعد والقمح والسلاح.", target: "east", tier: 3, weight: 1 },
  { text: "الانضمام للتحالف الدولي ضد داعش شرط للاعتراف الغربي.", target: "west", tier: 3, weight: 1 },
  { text: "(افتراضي) لو عُرض على سوريا الانضمام لتحالف دفاعي خليجي كاتفاق مكة، فيجب أن تنضم.", target: "gulf", tier: 3, weight: 1 },
  { text: "تركيا هي الضامن الأهم لأمن سوريا الشمالي.", target: "turkish", tier: 3, weight: 1 },
  { text: "التحالف مع إيران وروسيا يحمي سوريا من العزلة.", target: "east", tier: 3, weight: 1 },
  { text: "وجود قواعد أميركية أو تركية على الأرض غير مقبول.", target: "neutral", tier: 3, weight: 1 },
  { text: "يجب إبقاء سوريا غير منحازة والابتعاد عن محاور الصراع.", target: "neutral", tier: 3, weight: 1 },
  { text: "يجب تطبيع العلاقات مع إسرائيل مقابل انسحابها من الجنوب.", target: "west", tier: 3, weight: 1 },
  { text: "تدعم سوريا العقوبات الغربية على إيران وتنسّق مع واشنطن للحدّ من نفوذها الإقليمي.", target: "west", tier: 1, weight: 1.5 },
  { text: "تُبرم دمشق اتفاقية تدريب وتسليح مع دول أوروبية وباتحاد شمال الأطلسي.", target: "west", tier: 1, weight: 1.5 },
  { text: "تقبل الدولة تمويلاً خليجياً لإعادة الإعمار مقابل ترتيبات أمنية ترعاها دول الخليج.", target: "gulf", tier: 1, weight: 1.5 },
  { text: "تتبنّى دمشق الموقف الخليجي في مواجهة التمدد الإيراني في اليمن والمنطقة.", target: "gulf", tier: 1, weight: 1.5 },
  { text: "تُبرم دمشق اتفاقية دفاع مشترك مع تركيا تتضمّن وجوداً عسكرياً تركياً في الشمال.", target: "turkish", tier: 2, weight: 1.5 },
  { text: "تنسّق سوريا وتركيا عودة اللاجئين وتنظيم التجارة عبر المعابر الحدودية.", target: "turkish", tier: 2, weight: 1.5 },
  { text: "تشتري دمشق منظومات دفاع جوي روسية وتستقدم مستشارين روساً لتدريب الجيش.", target: "east", tier: 2, weight: 1.5 },
  { text: "تنضم سوريا إلى مبادرة الحزام والطريق وتقبل تمويلاً صينياً لمشاريع البنية التحتية.", target: "east", tier: 2, weight: 1.5 },
  { text: "تعتمد الحكومة على فصائل مدعومة إيرانياً لتأمين الحدود الشرقية والجنوبية.", target: "east", tier: 3, weight: 1.5 },
  { text: "تفضّل سوريا إطاراً دفاعياً عربياً مشتركاً على أي تحالف عسكري أجنبي.", target: "neutral", tier: 3, weight: 1.5 },
  { text: "تحافظ دمشق على مسافة متساوية من واشنطن وموسكو وطهران وأنقرة دون انحياز.", target: "neutral", tier: 3, weight: 1.5 },
];
